### ISSUE TITLE
add AuthPlugin as vue plugin

### ISSUE THREAD

**Issue by agentschmitt** [SamhammerAG/Samhammer.Authentication.Vue#2]
i think it would improve usage of AuthPlugin when we add the instance to vue by vue plugin install.
this would allow usage of  some public methods / properties directly in every vue instance:
some methods could be used very often vue components e.g. this.$auth.authenticated or this.$auth.hasRole

**Comment by domi2120** [comment]
it might be useful to separate the current AuthPlugin and a possible vue plugin to allow continued use in non vue projects. A separate vue plugin could import the AuthPlugin and install it to the vue instance, while still allowing the Plugin to be used outside of vue.

**Comment by agentschmitt** [comment]
not planned for now, as this would also add vuejs depenceny and currently we use it also in non-vue projects.
