### ISSUE TITLE
lodash treeshaking support

### ISSUE THREAD

**Issue by agentschmitt** [SamhammerAG/Samhammer.Authentication.Vue#22]
we should optimize our imports of lodash to allow treeshaking, as this results in lower bundle size.
their are multiple bundle tools supporting this. e.g. https://www.npmjs.com/package/@optimize-lodash/rollup-plugin

we should not do this:
```
import _ from "lodash;
_.join(values, ",")
```

instead we should do this:
```
import { join } from "lodash;
join(values, ",")
```

maybe also something like this should be fine
```
import join from "lodash/join;
join(values, ",")
```

**Comment by LeonSnajdr** [comment]
should be fixed by **https://samhammer.atlassian.net/browse/MET-2558**
